/*
 * This source file was generated by the Gradle 'init' task
 */
package car;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class CarTest {

    @Test void testGetMake() {
        Car c = new Car("Smart", "forTwo", 2016);
        assertEquals("Smart", c.getMake());
    }

    /*
     * TODO: write at least five more tests for the methods you implemented in
     * the Car class.
     */

}
